import { MavrykTheme } from 'utils/interfaces'

export const backgroundColor = '#160E3F' //'#FFFFFF'
export const containerColor = '#1C1C3F' //'#F7F9FD'
export const borderColor = '#4F457C'
export const textColor = '#fff' //'#000000'
export const subTextColor = '#fff' //'#29264C'
export const backgroundTextColor = '#191919'
export const placeholderColor = '#9090A0'
export const primaryColor = '#7068AA'
export const secondaryColor = '#73d7c3'
export const upColor = '#00E205'
export const downColor = '#F90021'
export const selectedColor = '#aea3ff3d'
export const btnLightColor = '#86D4C9'
export const headerColor = '#38237C'
export const subHeaderColor = '#8D86EB'
export const coralColor = '#FF8486'
export const titleColor = '#503EAA'
export const labelColor = '#77a4f2cc'
export const darkColor = '#080628'
export const skyColor = '#77A4F2'
export const cyanColor = '#86D4C9'
export const connectWalletSecondary = '#EEEAF4'
export const infoColor = '#00C2FF'
export const silverColor = '#C0DBFF'
export const warningColor = '#FF7A00'

export const darkMode: MavrykTheme = {
  whatMakesBackground: '/images/what-makes-dark.svg',
  calculatorBackground: '/images/calculator-bg-dark.svg',
  featuresBackground: '/images/features-bg-dark.svg',
  teamCityDecor: '/images/team/team-city-dark.svg',
  teamDecor1: '/images/team/team-decor-1-dark.svg',
  teamDecor2: '/images/team/team-decor-2-dark.svg',
  teamDecor3: '/images/team/team-decor-3-dark.svg',
  teamDecor4: '/images/team/team-decor-4-dark.svg',
  subscribeBachground: '/images/subscribe-bg-dark.svg',
  starsBachground: '/images/stars-bg-dark.svg',
  satellitesGradient: 'linear-gradient(180deg, #160E3F 3.55%, #321F71 103.84%);',
  skyGradientTransparent:
    'linear-gradient(0deg, #285A8A 8.7%, #38237C 42.22%, #2D1C6A 52.19%, #221555 68.5%, #1B1149 83.9%, #160E3F00 99.3%)',
  skyGradient:
    'linear-gradient(0deg, #285A8A 8.7%, #38237C 42.22%, #2D1C6A 52.19%, #221555 68.5%, #1B1149 83.9%, #160E3F 99.3%)',
  backgroundColor,
  containerColor,
  textColor,
  subTextColor: '#fff',
  placeholderColor: '#F7F9FD',
  primaryColor: '#7068AA',
  upColor: '#00E205',
  downColor: '#F90021',
  litepaperLinkColor: '#73d7c3',
  navColor: '#86D4C9',
  inputBorderColor: titleColor,
  headerTeam: '#fff',
  headerColor: '#fff',
  headerSectionsColor: '#fff',
  headerDarkColor: '#fff',
  darkestBackroundColor: '#080628',
  darkBackroundColor: '#160E3F',
  labelColor,
  headingColor: subHeaderColor,
  btnBackroundColor: btnLightColor,
  btnColor: backgroundColor,
  linkedinLinkColor: '#77A4F2',
  socialBackroundColor: '#503EAA',
  socialColor: '#C0DBFF',
  inputColor: subHeaderColor,
  btnBackroundNewsColor: '#86D4C9',
  btnNewsColor: '#38237C',
  inputNewsBg: 'rgba(8, 6, 40, 0.5)',
  inputNewsColor: '#77A4F2',
  roadmapValueColor: '#77A4F2',
  arrowStrokeColor: '#8D86EB',
  socialsColor: '#EBF0FF',
  lbBorder: '#503EAA',
  toggleButtonBg: 'transparent',
  toggleButtonColor: '#8D86EB',
  toggleButtonColorSelected: '#160E3F',
  toggleButtonBgSelected: '#8D86EB',
  inputTextColor: '#c0dbff',
  settingsConfigmBG: cyanColor,
  topBarLinkColor: cyanColor,
  topBarLinkColorActive: '#8D86EB',
  infoColor: '#00C2FF',
  warningColor: '#FF7A00',
  actionPrimaryBtnColor: cyanColor,
  tooltipColor: '#9EA9E8',
  tooltipBg: '#38237C',
  priceImpact: cyanColor,
  footerText: silverColor,
  theme: 'dark',
}

export const lightMode: MavrykTheme = {
  whatMakesBackground: '/images/what-makes-light.svg',
  calculatorBackground: '/images/calculator-bg-light.svg',
  featuresBackground: '/images/features-bg-light.svg',
  teamCityDecor: '/images/team/team-city-light.svg',
  teamDecor1: '/images/team/team-decor-1-light.svg',
  teamDecor2: '/images/team/team-decor-2-light.svg',
  teamDecor3: '/images/team/team-decor-3-light.svg',
  teamDecor4: '/images/team/team-decor-4-light.svg',
  subscribeBachground: '/images/subscribe-bg-light.svg',
  starsBachground: '/images/stars-bg-light.svg',
  satellitesGradient: 'linear-gradient(180deg, #FFFFFF 48.18%, #86D4C9 103.84%)',
  skyGradientTransparent: 'linear-gradient(0deg, #77A4F2 8.7%, #FFFFFF 99.3%)',
  skyGradient: 'linear-gradient(0deg, #77A4F2 8.7%, #FFFFFF 99.3%)',
  backgroundColor: '#fff',
  containerColor: '#DEE7F7',
  textColor: '#080628',
  subTextColor: '#29264C',
  placeholderColor: '#7068AA',
  primaryColor: '#7068AA',
  upColor: 'green',
  downColor: '#F90021',
  litepaperLinkColor: '#7068AA',
  navColor: titleColor,
  inputBorderColor: '#C0DBFF',
  headerColor,
  darkestBackroundColor: '#ebf0ff',
  darkBackroundColor: '#fff',
  labelColor: titleColor,
  headingColor: titleColor,
  headerSectionsColor: titleColor,
  btnBackroundColor: titleColor,
  btnBackroundNewsColor: '#38237C',
  linkedinLinkColor: '#160E3F',
  socialBackroundColor: '#F7F9FD',
  socialColor: headerColor,
  inputColor: titleColor,
  btnColor: '#F7F9FD',
  headerDarkColor: headerColor,
  roadmapValueColor: headerColor,
  headerTeam: '#27007A',
  priceImpact: '#27007A',
  btnNewsColor: '#fff',
  inputNewsBg: 'rgba(255, 255, 255, 0.5)',
  inputNewsColor: '#080628',
  arrowStrokeColor: '#77A4F2',
  socialsColor: headerColor,
  lbBorder: '#77A4F2',
  toggleButtonBg: '#EBF0FF',
  toggleButtonColor: '#27007A',
  toggleButtonColorSelected: '#FFFFFF  ',
  toggleButtonBgSelected: '#503EAA',
  inputTextColor: '#503EAA',
  settingsConfigmBG: 'transparent',
  topBarLinkColor: '#27007A',
  topBarLinkColorActive: '#77A4F2',
  infoColor: '#00C2FF',
  warningColor: '#FF7A00',
  actionPrimaryBtnColor: cyanColor,
  tooltipColor: '#9EA9E8',
  tooltipBg: '#38237C',
  footerText: '#38237C',
  theme: 'light',
}

export const spaceMode: MavrykTheme = {
  whatMakesBackground: '/images/what-makes-light.svg',
  calculatorBackground: '/images/calculator-bg-light.svg',
  featuresBackground: '/images/features-bg-light.svg',
  teamCityDecor: '/images/team/team-city-light.svg',
  teamDecor1: '/images/team/team-decor-1-light.svg',
  teamDecor2: '/images/team/team-decor-2-light.svg',
  teamDecor3: '/images/team/team-decor-3-light.svg',
  teamDecor4: '/images/team/team-decor-4-light.svg',
  subscribeBachground: '/images/subscribe-bg-light.svg',
  starsBachground: '/images/stars-bg-light.svg',
  satellitesGradient: 'linear-gradient(180deg, #FFFFFF 48.18%, #86D4C9 103.84%)',
  skyGradientTransparent: 'linear-gradient(0deg, #77A4F2 8.7%, #FFFFFF 99.3%)',
  skyGradient: 'linear-gradient(0deg, #77A4F2 8.7%, #FFFFFF 99.3%)',
  backgroundColor: '#fff',
  containerColor: '#DEE7F7',
  textColor: '#080628',
  subTextColor: '#29264C',
  placeholderColor: '#7068AA',
  primaryColor: '#7068AA',
  upColor: 'green',
  downColor: '#F90021',
  litepaperLinkColor: '#7068AA',
  navColor: titleColor,
  inputBorderColor: '#C0DBFF',
  headerColor,
  darkestBackroundColor: '#ebf0ff',
  darkBackroundColor: '#fff',
  labelColor: titleColor,
  headingColor: titleColor,
  headerSectionsColor: titleColor,
  btnBackroundColor: titleColor,
  btnBackroundNewsColor: '#38237C',
  linkedinLinkColor: '#160E3F',
  socialBackroundColor: '#F7F9FD',
  socialColor: headerColor,
  inputColor: titleColor,
  btnColor: '#F7F9FD',
  headerDarkColor: headerColor,
  roadmapValueColor: headerColor,
  headerTeam: '#27007A',
  btnNewsColor: '#fff',
  inputNewsBg: 'rgba(255, 255, 255, 0.5)',
  inputNewsColor: '#080628',
  arrowStrokeColor: '#77A4F2',
  socialsColor: headerColor,
  lbBorder: '#77A4F2',
  toggleButtonBg: '#EBF0FF',
  toggleButtonColor: '#27007A',
  toggleButtonColorSelected: '#FFFFFF  ',
  toggleButtonBgSelected: '#503EAA',
  inputTextColor: '#503EAA',
  settingsConfigmBG: 'transparent',
  topBarLinkColor: cyanColor,
  topBarLinkColorActive: '#8D86EB',
  infoColor: '#00C2FF',
  warningColor: '#FF7A00',
  actionPrimaryBtnColor: cyanColor,
  tooltipColor: '#9ea9e8',
  tooltipBg: '#38237C',
  priceImpact: cyanColor,
  footerText: silverColor,
  theme: 'space',
}

export default {
  light: lightMode,
  dark: darkMode,
  space: spaceMode,
}
